### get me
GET http://localhost:3000/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzIwNTU2NjQ5LCJleHAiOjE3MjMyMzUwNDl9.sEoyO5scYVmp6qd5JhriU8PGZtGFR07cbChTcQFzkG8

### Get user by id
GET http://localhost:3000/auth/2

### get users by email
GET http://localhost:3000/auth/?email=test@test.test

### delete user given id
DELETE http://localhost:3000/auth/1

### update user given id
PATCH http://localhost:3000/auth/4
Content-Type: application/json

{
  "email": "test@test.test"
}